version: '3.7'

services:
  mysql:
    container_name: 'mysql'
    image: mysql-recipe-app
    env_file:
      - .env
    platform: linux/amd64
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    volumes:
      - ./.docker/mysql/db:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./.docker/mysql/log:/var/log/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      DB_NAMES: $DB_DATABASE
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: always
    tty: true
    networks:
      recipe-app:
        aliases:
          - mysql

  localstack:
    container_name: 'localstack'
    image: localstack-recipe-app
    env_file:
      - .env
    platform: linux/amd64
    build:
      context: .
      dockerfile: .docker/localstack/Dockerfile
    volumes:
      - ./.docker/localstack:/tmp/localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      - AWS_DEFAULT_OUTPUT=json
      - AWS_ACCESS_KEY_ID=$AWS_S3_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_S3_SECRET_ACCESS_KEY
      - DATA_DIR=/tmp/localstack/data
    ports:
      - '8000:8080'
      - '4567-4578:4567-4578'
      - '4579:4579'
    networks:
      recipe-app:
        aliases:
          - localstack

networks:
  recipe-app:
    driver: bridge
